tools:
  maven: 3.3.9
  jdk: 1.8.0_102-b14
envs:
  global:
    variables:
      test: Hello random %{(Math.abs(new java.util.Random().nextInt()) % 100000000 + 1).intValue()}
flows:
  master:
    - ws_snapshot: main
      excludes: target/**
    - parallel:
      - (on centos, noWorkspace) sleep 10
      - (on centos, exclusive):
        - ws_restore: main
        - echo ${test}
        - mvn clean package -B
  pr:
    - call: master
